### PR TITLE
Follow standard practice for modules with ArgumentParser

### PR DESCRIPTION
**Pull request by tashrifbillah**

### CODE REVIEW

**Comment by kcho** [comment]
I'd rather keep the `argparse` part as a separated function, to make it testable independently from `dpanonymize`. See below for how the test has been separated in the test code. 

https://github.com/AMP-SCZ/dpanonymize/blob/7928e687e649ae1fcf9e7e1c44530a97a2cb5c9d/tests/scripts/test_dpanon.py#L136-L147

**Comment by tashrifbillah** [comment]
That test fails! You haven't updated that test after removing argument from `parse_args()`.

**Comment by kcho** [comment]
@tashrifbillah Thanks. I'll be working on it soon.

**Comment by tashrifbillah** [comment]
> I'd rather keep the argparse part as a separated function

Undid my change, thanks.

**Comment by kcho** [comment]
> That test fails! You haven't updated that test after removing argument from `parse_args()`.

fixed 

```
```

**Pull request closed without merging**
